name: Flyway Migrations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo so we have access to the migration scripts
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java (required by Flyway)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Step 3: Run Flyway migrations
      - name: Run Flyway
        uses: flyway/flyway-action@v2
        with:
          url: jdbc:postgresql://192.168.2.102:5432/cms
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          schemas: penguin
          locations: filesystem:db/migrations
