name: Flyway Migrations

on:
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: [self-hosted, windows]

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Flyway CLI
      - name: Set up Flyway
        run: |
          Invoke-WebRequest -Uri https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.32.0/flyway-commandline-10.32.0-windows-x64.zip -OutFile flyway.zip
          Expand-Archive flyway.zip -DestinationPath flyway
          $env:Path += ";$PWD\flyway\flyway-10.32.0"
        shell: pwsh

      # 3. Run Flyway migrations
      - name: Run Flyway Migrations
        env:
          FLYWAY_URL: jdbc:postgresql://192.168.2.102:5432/cms
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FLYWAY_SCHEMAS: penguin
        run: |
          flyway -locations=filesystem:db/migrations migrate
        shell: pwsh
