name: Flyway Migrations

on:
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flyway CLI
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.11.1/flyway-commandline-11.11.1-linux-x64.tar.gz -o flyway.tar.gz
          tar -xzf flyway.tar.gz
          export PATH="$PWD/flyway-11.11.1:$PATH"

      - name: Run Flyway Migrations
        env:
          FLYWAY_URL: jdbc:postgresql://192.168.2.102:5432/cms
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FLYWAY_SCHEMAS: public
        run: |
          ./flyway-11.11.1/flyway -locations=filesystem:./db/migrations -schemas=$FLYWAY_SCHEMAS -baselineOnMigrate=true migrate

