name: Flyway Migrations

on:
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: [self-hosted, windows]

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set Flyway Path
      - name: Set Flyway Path
        shell: powershell
        run: |
          $env:PATH += ";C:\flyway-11.11.0"

      # 3. Run Flyway Migrations
      - name: Run Flyway Migrations
        shell: powershell
        env:
          FLYWAY_URL: jdbc:postgresql://192.168.2.102:5432/cms
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FLYWAY_SCHEMAS: penguin
        run: |
          flyway.cmd -locations=filesystem:db/migrations migrate
