name: Flyway Migrations

on:
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: [self-hosted, windows]

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Download and extract Flyway CLI
      - name: Set up Flyway
        shell: powershell
        run: |
          $flywayUrl = "https://github.com/flyway/flyway/releases/download/flyway-11.11.1/flyway-commandline-11.11.1-windows-x64.zip"
          $flywayZip = "$env:TEMP\flyway.zip"
          Invoke-WebRequest -Uri $flywayUrl -OutFile $flywayZip
          Expand-Archive -Path $flywayZip -DestinationPath "$env:TEMP\flyway"
          $env:PATH += ";$env:TEMP\flyway\flyway-11.11.1"

      # 3. Run Flyway migrations
      - name: Run Flyway Migrations
        shell: powershell
        env:
          FLYWAY_URL: jdbc:postgresql://192.168.2.102:5432/cms
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FLYWAY_SCHEMAS: penguin
        run: |
          flyway -locations=filesystem:db/migrations migrate
