name: Flyway Migrations

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  migrate:
    runs-on: windows-latest

    env:
      FLYWAY_URL: jdbc:postgresql://192.168.2.102:5432/cms
      FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
      FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
      FLYWAY_SCHEMAS: penguin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Flyway
        run: |
          Write-Host "Downloading Flyway..."
          Invoke-WebRequest -Uri https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.11.0/flyway-commandline-11.11.0-windows-x64.zip -OutFile flyway.zip
          Expand-Archive flyway.zip -DestinationPath C:\flyway
          $env:PATH += ";C:\flyway\flyway-11.11.0"

      - name: List migration files
        run: dir .\db\migrations

      - name: Check DB connectivity
        run: |
          Write-Host "Checking DB connection..."
          $connection = Test-Connection -ComputerName 192.168.2.102 -Count 2 -Quiet
          if (-not $connection) { throw "Database server not reachable!" }

      - name: Run Flyway migrations
        run: |
          Write-Host "Running Flyway migrations..."
          & "C:\flyway\flyway-11.11.0\flyway.exe" migrate `
            -url=$env:FLYWAY_URL `
            -user=$env:FLYWAY_USER `
            -password=$env:FLYWAY_PASSWORD `
            -schemas=$env:FLYWAY_SCHEMAS `
            -baselineOnMigrate=true `
            -locations=filesystem:./db/migrations `
            -X
