name: Flyway Migrations

on:
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify migration files
        run: dir .\db\migrations

      - name: Verify database connection
        env:
          FLYWAY_URL: jdbc:postgresql://192.168.2.102:5432/cms
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Checking database connection..."
          psql "$env:FLYWAY_URL" -U "$env:FLYWAY_USER" -c "\conninfo"


      - name: Run Flyway Migrations
        env:
          FLYWAY_URL: jdbc:postgresql://192.168.2.102:5432/cms
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FLYWAY_SCHEMAS: penguin
          FLYWAY_LOCATIONS: filesystem:./db/migrations
        run: |
          echo "Running Flyway migrations..."
          C:/flyway-11.11.0/flyway migrate `
            -X `
            -url="$env:FLYWAY_URL" `
            -user="$env:FLYWAY_USER" `
            -password="$env:FLYWAY_PASSWORD" `
            -schemas="$env:FLYWAY_SCHEMAS" `
            -baselineOnMigrate=true `
            -locations="$env:FLYWAY_LOCATIONS"
